version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    container_name: web-postgres
    environment:
      POSTGRES_DB: "express"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      APPLICATION_DB_USER: "app_user"
      APPLICATION_DB_INITIAL_PASSWORD: "app_user_password"
    ports:
      - "5432:5432"
  node-app:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8081:8081"
    environment:
      POSTGRES_DB: "express"
      POSTGRES_HOST: "web-postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      APPLICATION_DB_USER: "app_user"
      APPLICATION_DB_INITIAL_PASSWORD: "app_user_password"
